name: vmflow-mqtt

services:
  broker:
    image: eclipse-mosquitto:latest
    networks:
      - vmflow-net    
    restart: unless-stopped
    ports:
      - "1883:1883"   # MQTT (TCP)
      - "9001:9001"   # WebSockets (opcional)
    volumes:
      - ./mqtt/config:/mosquitto/config
      - mqtt-data:/mosquitto/data
      #- ./volumes/mqtt/log:/mosquitto/log

  domain:
    build:
      dockerfile: ./mqtt/Dockerfile
    restart: unless-stopped
    networks:
      - vmflow-net
    depends_on:
      - broker
    volumes:
      - ./mqtt/clients:/clients
    working_dir: /clients
    environment:
      SUPABASE_PUBLIC_URL: ${SUPABASE_PUBLIC_URL}
      SERVICE_ROLE_KEY: ${SERVICE_ROLE_KEY}
      MQTT_HOST: broker

volumes:
  db-config:
  mqtt-data:


networks:
  vmflow-net:
    name: vmflow-net
    external: true

